name: release

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: big
    timeout-minutes: 15
    permissions:
      contents: read
    env:
      RUSTFLAGS: "-C debuginfo=0"
      CARGO_TARGET_DIR: target/ci
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set up rust
        uses: dtolnay/rust-toolchain@stable

      - name: cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: v0-rust-release
          cache-targets: true

      - name: doc build
        env:
          RUSTDOCFLAGS: "--cfg docsrs"
          CARGO_PROFILE_DEV_DEBUG: 0
        run: cargo doc --workspace --all-features --no-deps

      - name: run tests
        run: cargo test

      - name: install sbom tool
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-cyclonedx

      - name: generate sbom
        run: |
          for manifest in crates/*/Cargo.toml; do
            cargo cyclonedx --manifest-path "$manifest" --format json --override-filename "sbom-${{ github.ref_name }}.cdx" --all-features
          done

      - name: upload sbom
        uses: actions/upload-artifact@v4
        with:
          name: sbom-${{ github.ref_name }}
          path: "crates/**/sbom-${{ github.ref_name }}.cdx.json"

      - name: publish nautobot-openapi
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish -p nautobot-openapi --no-verify

      - name: publish nautobot
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish -p nautobot --no-verify

      - name: publish nautobot-cli
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish -p nautobot-cli --no-verify
